### ISSUE TITLE
LateInitializationError after adding first note

### ISSUE THREAD

**Issue by Ajaysinh1290** [iahmadamin/flutter_note_app#4]
Getting below error on Homepage after adding first note...!
```
======== Exception caught by widgets library =======================================================
The following LateError was thrown building Obx(has builder, state: _ObxState#53436):
LateInitializationError: Field '_children@308042623' has not been initialized.

The relevant error-causing widget was: 
  Obx Obx:file:///home/ajaysinh/AndroidStudioProjects/flutter_note_app/lib/ui/pages/home_page.dart:92:14
When the exception was thrown, this was the stack: 
#0      MultiChildRenderObjectElement._children (package:flutter/src/widgets/framework.dart)
#1      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6473:33)
#2      Element.debugDescribeChildren (package:flutter/src/widgets/framework.dart:4576:5)
#3      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:3003:48)
#4      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1219:43)
#5      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1151:14)
#6      DiagnosticsNode.toStringDeep.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1816:9)
#7      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1823:6)
```

**Comment by Ajaysinh1290** [comment]
Working on this issue...!
